CREATE TABLE IF NOT EXISTS cliente(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(6), 
    nome varchar(100) NOT NULL,
    cpf varchar(11),
    rg varchar(10),
    telefone varchar(15),
    celular varchar(15),
    email varchar(50),
    empresa varchar(50),
    cidade varchar(100),
    uf varchar(2)
);

CREATE TABLE IF NOT EXISTS hotel(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    razao_social varchar(100) NOT NULL,
    cnpj varchar(50) NOT NULL,
    endereco varchar(50),
    numero_endereco varchar(6),
    bairro varchar(50),
    cidade varchar(100),
    uf varchar(2),
    telefone varchar(15)
);

CREATE TABLE IF NOT EXISTS recebimento(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parcela integer NOT NULL,
    valor_total float NOT NULL,
    tipo_recebimento varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS apartamento(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hotel_id integer REFERENCES hotel(id),
    descricao varchar(50),
    numero_apartamento integer NOT NULL,
    telefone varchar(15),
    cama_solteiro varchar(10),
    cama_casal varchar(10),
    qtd_cama_solteiro integer,
    qtd_cama_casal integer,
    diaria float NOT NULL
);

CREATE TABLE IF NOT EXISTS reserva(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cliente_id integer REFERENCES cliente(id),
    apartamento_id integer REFERENCES apartamento(id),
    recebimento_id integer REFERENCES recebimento(id),
    checkin varchar(15) NOT NULL,
    checkout varchar(15) NOT NULL,
    hora_checkin varchar(15) NOT NULL,
    hora_checkout varchar(15) NOT NULL
);
